sudo: true
language: python
python: 2.7
addons:
  firefox: "latest"
services:
    - docker
env:
  globals:
  - DJANGO_LIVE_TEST_SERVER_ADDRESS="localhost:9900-9999"
  matrix:
  - TEST_SUITE=lint
  - TEST_SUITE=ui MARK_EXPRESSION=smoke
  - TEST_SUITE=docker
matrix:
  fast_finish: true
install: travis_retry scripts/travis/install.sh
before_script: travis_retry scripts/travis/setup.sh
script: scripts/travis/dispatch.sh $TEST_SUITE
notifications:
  email: false
  irc:
    channels:
    - irc.mozilla.org#sumodev
    on_success: always
    on_failure: always
