version: '3.4'
services:
  web:
    image: mozmeao/kitsune:base-dev-latest
    command: ./manage.py runserver 0.0.0.0:8000
    user: ${UID:-kitsune}
    depends_on:
      - mariadb
      - elasticsearch
      - redis
    ports:
      - "8000:8000"
  mariadb:
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=kitsune
      - MYSQL_USER=kitsune
      - MYSQL_PASSWORD=kitsune
      - MYSQL_DATABASE=kitsune
    entrypoint:
      - docker-entrypoint.sh
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - mysqlvolume:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - discovery.type=single-node
      - http.cors.allow-origin="http://127.0.0.1:1358"
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  redis:
    image: redis:3

volumes:
    mysqlvolume:
    esdata1:
